### ISSUE TITLE
Agricraft Pre-Release A20 NoSuchMethod Crash

### ISSUE THREAD

**Issue by Hypocrita20XX** [mallrat208/Multifarm-Crops#6]
Hey, first of all thank you for taking the time to make this mod!

Unfortunately, I can't get it to function without an immediate crash when the Forestry farm attempts to harvest the crop.
[Here's the crash log.](https://pastebin.com/raw/KAcixpXW)

If any other info is needed, let me know. =-)
Thanks!

**Comment by mallrat208** [comment]
I'll give a look at this as soon as I have some time and see what's happening

**Comment by mallrat208** [comment]
Actually, I would if I had access to that version of AgriCraft. Curseforge only has a19.

**Comment by Hypocrita20XX** [comment]
It's not fully released yet, so that may be why I was having this issue.

Here's a link to the download.
https://github.com/AgriCraft/AgriCraft/releases

**Comment by mallrat208** [comment]
Alright...

Further investigation has turned up nothing. I've been unable to reproduce this crash in development using the latest versions of Forge, Forestry, InfinityLib, and Agricraft A20 for 1.10.2.  

I'm going to go ahead and build a version of MFC specifically using A20 to see if it makes a difference. If you're up to it you can give it a test, otherwise I'm not pushing this until A20 is released.

https://github.com/mallrat208/Multifarm-Crops/releases/tag/1.1.2

**Comment by Hypocrita20XX** [comment]
Gave it a test with the smallest Forestry farm and some Torcherinos, it's all harvesting perfectly now, no crashes whatsoever.

Thanks for the work! =-)
